worker_processes 1;
pid /data/data/com.termux/files/home/nginx.pid;
error_log /data/data/com.termux/files/home/nginx-error.log;
events { worker_connections 2048; }
http {
    include /data/data/com.termux/files/usr/etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    sendfile_max_chunk 2m;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    gzip on;
    gzip_min_length 512;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/markdown;
    output_buffers 4 64k;

    server {
        listen 127.0.0.1:5000;
        listen [::]:5000 ipv6only=on;
        listen [::]:8443 ssl ipv6only=on;
        server_name direct.yousa.ccwu.cc;

        ssl_certificate /data/data/com.termux/files/home/.ssl/direct.yousa.ccwu.cc.fullchain.pem;
        ssl_certificate_key /data/data/com.termux/files/home/.ssl/direct.yousa.ccwu.cc.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        client_max_body_size 32m;
        proxy_request_buffering off;

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 600;
            proxy_buffering off;
        }
    }
}
